### ISSUE TITLE
Round before 0 check and confirmation

### ISSUE THREAD

**Issue by jmank88** [turbowallet/support#1]
Attempts to send `0` are rejected:
![screenshot from 2018-12-04 13-50-40](https://user-images.githubusercontent.com/1194128/49468867-a1d03a00-f7cb-11e8-92cf-ff62041c75b3.png)
But sending a very small value which rounds to 0 is accepted:
![screenshot from 2018-12-04 13-50-12](https://user-images.githubusercontent.com/1194128/49468879-aa287500-f7cb-11e8-9ac8-fcdb885bc69b.png)
The 0 check should occur after rounding, on the actual value that would be used, and this same value should be used in the confirmation message.

**Comment by treeder** [comment]
Prevents sending less than the minimum, eg: 1 WEI for GO/ETH.
